package main

import (
	"context"
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"

	"github.com/tuangatech/hacker-five/pkg/recon"
	"github.com/tuangatech/hacker-five/pkg/registry"
	"github.com/tuangatech/hacker-five/pkg/scanner/httpclient"
	"github.com/tuangatech/hacker-five/pkg/scanner/ratelimit"
	"github.com/tuangatech/hacker-five/pkg/scanner/scope"
	"github.com/tuangatech/hacker-five/pkg/templatesync"
)

// newPlanCmd wires pkg/recon and pkg/registry together end to end (doc14
// Step 3's R8): runs recon against target, then the deterministic decision
// engine, and prints the resulting PlanTree — the concrete, standalone,
// no-agent-required proof that a live ReconResult resolves to real
// PlanTree leaves with zero LLM calls (Decision 6).
func newPlanCmd(root *rootFlags) *cobra.Command {
	var (
		target        string
		depth         string
		scopeFile     string
		rateLimit     int
		concurrency   int
		insecure      bool
		templateIndex string
	)

	cmd := &cobra.Command{
		Use:   "plan",
		Short: "Run recon against a target, then resolve it to a PlanTree via the deterministic decision engine (no agent/LLM involved)",
		RunE: func(cmd *cobra.Command, args []string) error {
			if target == "" {
				return fmt.Errorf("--targets is required")
			}
			d := recon.Depth(depth)
			switch d {
			case recon.DepthPassive, recon.DepthActive, recon.DepthFull:
			default:
				return fmt.Errorf(`--recon-depth must be "passive", "active", or "full", got %q`, depth)
			}

			var s *scope.Scope
			if scopeFile != "" {
				parsed, err := scope.Parse(scopeFile)
				if err != nil {
					return fmt.Errorf("parsing --scope: %w", err)
				}
				s = parsed
			} else {
				_, _ = fmt.Fprintln(cmd.ErrOrStderr(), "warning: no --scope given — every host recon discovers is treated as in-scope")
			}

			// A missing template index degrades to skipping template-tag
			// matching, not a hard failure — the same "missing optional
			// input, warn and continue" posture pkg/recon already uses for
			// a missing binary.
			var index []templatesync.Entry
			if entries, err := loadTemplateIndex(templateIndex); err != nil {
				_, _ = fmt.Fprintf(cmd.ErrOrStderr(), "warning: could not load %s (%v) — template-tag matching skipped; run 'hackerfive templates index' first\n", templateIndex, err)
			} else {
				index = entries
			}

			client := httpclient.New(httpclient.Config{
				Timeout:             root.timeout,
				MaxRedirects:        5,
				InsecureSkipVerify:  insecure,
				MaxIdleConnsPerHost: concurrency,
				ProxyURL:            root.proxy,
			}, httpclient.WithRateLimit(ratelimit.New(rateLimit)))

			opts := []recon.Option{recon.WithRateLimit(rateLimit), recon.WithConcurrency(concurrency)}
			if s != nil {
				opts = append(opts, recon.WithScope(s))
			}
			r := recon.New(client, opts...)

			ctx, cancel := context.WithTimeout(cmd.Context(), reconRunTimeout)
			defer cancel()

			result, err := r.Run(ctx, target, d)
			if err != nil {
				return fmt.Errorf("running recon: %w", err)
			}

			tree := registry.Resolve(result, index)

			out := cmd.OutOrStdout()
			if root.output != "" {
				f, err := os.Create(root.output)
				if err != nil {
					return fmt.Errorf("opening output file: %w", err)
				}
				defer func() { _ = f.Close() }()
				out = f
			}
			enc := json.NewEncoder(out)
			enc.SetIndent("", "  ")
			return enc.Encode(tree)
		},
	}

	cmd.Flags().StringVarP(&target, "targets", "t", "", "target URL to run recon against, then plan (required)")
	cmd.Flags().StringVar(&depth, "recon-depth", "active", `how far recon escalates before planning: "passive", "active" (default — Wave 2's httpx tech signals are what the decision engine matches against), "full"`)
	cmd.Flags().StringVar(&scopeFile, "scope", "", "path to a target allow-list file (same format as scan's --scope); omitted = every discovered host is treated as in-scope, with a warning")
	cmd.Flags().IntVar(&rateLimit, "rate-limit", recon.DefaultRateLimit, "requests/sec passed to each external recon binary's own native rate-limit flag")
	cmd.Flags().IntVarP(&concurrency, "concurrency", "c", recon.DefaultConcurrency, "concurrency passed to each external recon binary's own native concurrency flag")
	cmd.Flags().BoolVar(&insecure, "insecure", false, "skip TLS verification for this package's own direct HTTP calls — lab targets only, never the default")
	cmd.Flags().StringVar(&templateIndex, "template-index", "templates/index.json", "path to the index generated by 'hackerfive templates index' — missing file degrades to skipping template-tag matching, not a hard failure")

	return cmd
}
